########
# Copyright (c) 2014 GigaSpaces Technologies Ltd. All rights reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
#    * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    * See the License for the specific language governing permissions and
#    * limitations under the License.

# -*- mode: ruby -*-
# vi: set ft=ruby :

AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
AWS_ACCESS_KEY = ENV['AWS_ACCESS_KEY']

HUBOT_CONTAINER_REPO = ENV['HUBOT_CONTAINER_REPO']
HUBOT_FLOWDOCK_LOGIN_EMAIL = ENV['HUBOT_FLOWDOCK_LOGIN_EMAIL']
HUBOT_FLOWDOCK_LOGIN_PASSWORD = ENV['HUBOT_FLOWDOCK_LOGIN_PASSWORD']

BASE_BOX_NAME = 'ubuntu/trusty64'

Vagrant.configure('2') do |config|

  config.vm.define "hubot_aws" do |hubot_aws|
    #dummy box, will be overriden
    hubot_aws.vm.box = "dummy"
    hubot_aws.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    hubot_aws.vm.provider :aws do |aws, override|
      aws.access_key_id = AWS_ACCESS_KEY_ID
      aws.secret_access_key = AWS_ACCESS_KEY

      # official ubuntu 14.04 64bit box
      aws.ami = "ami-0307d674"
      aws.region = "eu-west-1"
      aws.instance_type = "m1.small"

      aws.keypair_name = "vagrant_build"
      override.ssh.username = "ubuntu"
      override.ssh.private_key_path = "~/.ssh/aws/vagrant_build.pem"

      aws.tags = {
          "Name" => "vagrant cloudify hubot",
      }
        aws.security_groups = "vagrant_cfy_build"
    end

    # need to sync folders
    hubot_aws.vm.synced_folder "../", "/cloudify-hubot", create: true
    hubot_aws.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "#{HUBOT_FLOWDOCK_LOGIN_EMAIL} #{HUBOT_FLOWDOCK_LOGIN_PASSWORD}"
      s.privileged = false
    end
  end

  config.vm.define :hubot_vbox do |hubot_vbox|
    hubot_vbox.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '1024']
    end
    hubot_vbox.vm.box = BASE_BOX_NAME
    hubot_vbox.vm.hostname = 'hubot-vbox'
    hubot_vbox.vm.synced_folder "../", "/cloudify-hubot", create: true
    hubot_vbox.vm.provision "shell" do |s|
      s.path = "provision.sh"
      s.args = "#{HUBOT_CONTAINER_REPO} #{HUBOT_FLOWDOCK_LOGIN_EMAIL} #{HUBOT_FLOWDOCK_LOGIN_PASSWORD}"
      s.privileged = false
    end
  end
end
